language: c

addons:
  apt:
    sources:
      # add PPAs with more up-to-date toolchains
      - sourceline: 'ppa:ubuntu-toolchain-r/test'

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-5
  - sudo update-alternatives --quiet --install /usr/bin/gcc gcc /usr/bin/gcc-5 60

script:
  - make -C php_agent axiom-run-tests
  - make test_app
  - make run_tests
